import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <div className="container mx-auto">
                    <h1 className="text-3xl font-bold text-center mt-10">
                        Hi, I&apos;m <span className="text-pink-600">Shenita</span>.
                    </h1>

                    <p className="text-center mt-3">
                        I&apos;m a front-end developer based in London.
                    </p>
                </div>
            </main>
        </div>
    )
}
